### ISSUE TITLE
Problema com o script (grid.table)

### ISSUE THREAD

**Issue by gnramos** [rnmourao/women_computer_science#4]
A execução do código das linhas 179-183 ([script.R](../blob/master/src/script.R)) resulta no seguinte erro:

Error in grid.Call(L_getEngineDLon) :
non-finite location and/or size for viewport
Calls: grid.table -> grid.draw -> grid.draw.gTree -> grid.Call
Execution halted

**Comment by rnmourao** [comment]
Não estou conseguindo reproduzir o erro: os gráficos foram gerados.

Pode ser uma diferença de implementação do sistema operacional... acontece
algumas vezes com R. Estou usando Ubuntu 16.

Posso alterar o comando para usar sink() ao invés de pdf(), mas a saída
seria um arquivo texto.

Como o teste de Tukey é fundamental para a análise, posso deixar as imagens
compactadas no Github até encontrarmos o motivo do problema.

Att.,

Roberto.

Em 6 de fev de 2017 11:08 AM, "gnramos" <notifications@github.com> escreveu:

A execução do código das linhas 179-183 (script.R
<http://../blob/master/src/script.R>) resulta no seguinte erro:

Error in grid.Call(L_getEngineDLon) :
non-finite location and/or size for viewport
Calls: grid.table -> grid.draw -> grid.draw.gTree -> grid.Call
Execution halted

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rnmourao/women_computer_science/issues/4>, or mute the
thread

**Comment by gnramos** [comment]
Pode ser problema de versão, mas isso precisa ser identificado para que o experimento possa ser reproduzido.

Minha versão: R version 3.3.2 (2016-10-31)
(Ubuntu 16.04.1 LTS 64-bit)

**Comment by rnmourao** [comment]
Minha versão de R é mais antiga: 3.2.3.
Vou atualizar e tentar reproduzir o problema.
Minha preocupação é que não achei ninguém com esse erro no Google...


Em 6 de fev de 2017 3:19 PM, "gnramos" <notifications@github.com> escreveu:

**Comment by rnmourao** [comment]
Consegui resolver: problema estranho com NA no tratamento. Usei a função levels para resolver.
